# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Radib Bin Kabir\OneDrive\Desktop\RDBMS\Project\FrontendQLib\QLibrary\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(893, 711)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(1)
        Form.setFont(font)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(100, 60, 721, 591))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"background-color: rgba(85,98,112,255);\n"
"color: rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left: 5px;\n"
"padding-top:5px;\n"
"background-color: rgba(255,107,107,255);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color:rgba(255,107,107,255);\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(300, 60, 381, 471))
        self.label.setStyleSheet("/* Style for QLabel with a solid lightest blue background */\n"
"QLabel {\n"
"    background-color: #FFFFFF; /* Lightest blue background color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    padding: 10px; /* Padding around the content */\n"
"    color: #333333; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    text-align: center; /* Center-align text */\n"
"}\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 25, 341, 541))
        self.label_2.setStyleSheet("/* Style for QLabel with a darker gradient background */\n"
"QLabel {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 0, 128, 255), stop:1 rgba(0, 0, 128, 255));\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    padding: 10px; /* Padding around the content */\n"
"    color: #FFFFFF; /* Text color (white) */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    text-align: center; /* Center-align text */\n"
"}\n"
"\n"
"/* QLabel when hovered */\n"
"QLabel:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 128, 255), stop:1 rgba(85, 0, 128, 255));\n"
"}\n"
"\n"
"/* QLabel when clicked (pressed) */\n"
"QLabel:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(128, 0, 0, 255), stop:1 rgba(0, 0, 85, 255));\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(450, 130, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(0,0,0,200);\n"
"")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(420, 240, 211, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46, 82, 101, 200);\n"
"color:rgba(0,0,0);\n"
"padding-bottom:7px;")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(420, 320, 211, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46, 82, 101, 200);\n"
"color:rgba(0,0,0);\n"
"padding-bottom:7px;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(440, 430, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("/* Style for QPushButton with solid blue background and white text */\n"
"QPushButton {\n"
"    background-color: #0000A5; /* Solid blue background color */\n"
"    color: #FFFFFF; /* Text color (white) */\n"
"    border: 1px solid #333333; /* Border style */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Padding around the content */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 18px; /* Font size */\n"
"}\n"
"\n"
"/* QPushButton when hovered */\n"
"QPushButton:hover {\n"
"    background-color: #0b00d7; /* Slightly lighter blue on hover */\n"
"    color: yellow;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(60, 110, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("text-align:center;\n"
"color:rgba(255,255,255,220);\n"
"margin-left:center;\n"
"margin-right:center;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(80, 220, 261, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(444, 444))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: transparent;\n"
"border-radius:10px;")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setMidLineWidth(0)
        self.label_5.setText("")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setPixmap(QtGui.QPixmap("D:/Downloaded Files/books (2).png"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Log In"))
        self.lineEdit.setPlaceholderText(_translate("Form", "UserName"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "PassWord"))
        self.pushButton.setText(_translate("Form", "Log In"))
        self.label_4.setText(_translate("Form", "QLibrary"))
